# Generated by Django 2.0.3 on 2018-04-01 10:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('accountingApp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
