# Generated by Django 2.0.3 on 2018-04-01 11:52

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('accountingApp', '0002_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Capital',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
            ],
        ),
    ]
