# Generated by Django 2.0.3 on 2018-04-01 12:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accountingApp', '0003_capital'),
    ]

    operations = [
        migrations.AddField(
            model_name='capital',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE,
                                       to=settings.AUTH_USER_MODEL),
        ),
    ]
