# Generated by Django 2.0.3 on 2018-04-01 12:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('accountingApp', '0004_capital_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capital',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
