# Generated by Django 2.0.5 on 2018-05-27 13:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accountingApp', '0005_auto_20180401_1542'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, null=True)),
                ('type', models.CharField(
                    choices=[('credit_card', 'Credit Card'), ('bank_account', 'Bank Account'), ('cash', 'Cash')],
                    max_length=20)),
                ('balance', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='AccountingBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('balance', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='AccountingBookAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accountingApp.Account')),
                ('accounting_book',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accountingApp.AccountingBook')),
            ],
        ),
        migrations.CreateModel(
            name='AccountingBookUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accounting_book',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accountingApp.AccountingBook')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Installment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('amount', models.FloatField()),
                ('count', models.IntegerField()),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accountingApp.Account')),
                ('accounting_book', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING,
                                                      to='accountingApp.AccountingBook')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account',
                 models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='accountingApp.Account')),
                ('accounting_book', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING,
                                                      to='accountingApp.AccountingBook')),
            ],
        ),
        migrations.AddField(
            model_name='accountingbook',
            name='accounts',
            field=models.ManyToManyField(through='accountingApp.AccountingBookAccount', to='accountingApp.Account'),
        ),
        migrations.AddField(
            model_name='accountingbook',
            name='capital',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='accountingApp.Capital'),
        ),
        migrations.AddField(
            model_name='accountingbook',
            name='user',
            field=models.ManyToManyField(through='accountingApp.AccountingBookUser', to=settings.AUTH_USER_MODEL),
        ),
    ]
