# Generated by Django 2.1a1 on 2018-05-20 12:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accountingApp', '0007_account_transaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountingbook',
            name='user',
        ),
        migrations.AddField(
            model_name='accountingbook',
            name='user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
