# Generated by Django 2.1a1 on 2018-05-20 12:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('accountingApp', '0008_auto_20180520_1500'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='accounting_book',
        ),
        migrations.AddField(
            model_name='accountingbook',
            name='accounts',
            field=models.ManyToManyField(to='accountingApp.Account'),
        ),
        migrations.AlterField(
            model_name='accountingbook',
            name='balance',
            field=models.FloatField(default=0.0),
        ),
    ]
