# Generated by Django 2.1a1 on 2018-05-20 12:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('accountingApp', '0009_auto_20180520_1508'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='name',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='type',
            field=models.CharField(
                choices=[('credit_card', 'Credit Card'), ('bank_account', 'Bank Account'), ('cash', 'Cash')],
                max_length=20),
        ),
    ]
