# Generated by Django 2.1a1 on 2018-05-20 12:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('accountingApp', '0010_auto_20180520_1526'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='amout',
            new_name='amount',
        ),
    ]
