# Generated by Django 2.1a1 on 2018-05-20 13:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('accountingApp', '0012_auto_20180520_1546'),
    ]

    operations = [
        migrations.AddField(
            model_name='installment',
            name='accounting_book',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING,
                                    to='accountingApp.AccountingBook'),
        ),
    ]
